# Generated by Django 4.1.1 on 2022-09-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter', models.CharField(max_length=40)),
                ('mean', models.CharField(max_length=40)),
                ('dessert', models.CharField(max_length=40)),
                ('price', models.FloatField()),
            ],
        ),
    ]
