# Generated by Django 4.1.1 on 2022-09-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_rename_mean_menus_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='image',
            field=models.ImageField(null=True, upload_to='menus'),
        ),
    ]
